import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home';
import { AboutComponent } from './components/about/about';
import { FeaturesComponent } from './components/features/features';
import { HelpCenterComponent } from './components/help-center/help-center';
import { LoginComponent } from './components/login/login';
import { RegisterComponent } from './components/register/register';
import { MentorListingsComponent } from './components/mentor-listings/mentor-listings';
import { MentorProfileComponent } from './components/mentor-profile/mentor-profile';
import { BookingComponent } from './components/booking/booking';
import { BookSessionComponent } from './components/book-session/book-session';
import { StudentDashboardComponent } from './components/student-dashboard/student-dashboard';
import { MySessionsComponent } from './components/my-sessions/my-sessions';
import { MentorDashboardComponent } from './components/mentor-dashboard/mentor-dashboard';
import { MentorSessionsComponent } from './components/mentor-sessions/mentor-sessions';
import { AdminComponent } from './components/admin/admin';
import { AdminStudentsComponent } from './components/admin-students/admin-students';
import { AdminMentorsComponent } from './components/admin-mentors/admin-mentors';
import { AdminUsersComponent } from './components/admin-users/admin-users';
import { AdminSessionsComponent } from './components/admin-sessions/admin-sessions';
import { MentorAvailabilityComponent } from './components/mentor-availability/mentor-availability';
import { StudentAccountComponent } from './components/student-account/student-account';
import { StudentHelpAndSupportComponent } from './components/student-helpandsupport/student-helpandsupport';

export const routes: Routes = [
  { path: 'book-session', component: BookSessionComponent },
  { path: '', component: HomeComponent },
  { path: 'home', component: HomeComponent },
  { path: 'about', component: AboutComponent },
  { path: 'features', component: FeaturesComponent },
  { path: 'help-center', component: HelpCenterComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'mentors', component: MentorListingsComponent },
  { path: 'mentor-profile/:id', component: MentorProfileComponent },
  { path: 'mentor-profile', component: MentorProfileComponent },
  { path: 'booking/:mentorId', component: BookingComponent },
  { path: 'student-dashboard', component: StudentDashboardComponent },
  { path: 'student-account', component: StudentAccountComponent },
  { path: 'student-help', component: StudentHelpAndSupportComponent },
  { path: 'my-sessions', component: MySessionsComponent },
  { path: 'mentor-dashboard', component: MentorDashboardComponent },
  { path: 'mentor-sessions', component: MentorSessionsComponent },
  { path: 'mentor-availability', component: MentorAvailabilityComponent },
  { path: 'admin', component: AdminComponent },
  { path: 'admin/users', component: AdminUsersComponent },
  { path: 'admin/students', component: AdminStudentsComponent },
  { path: 'admin/mentors', component: AdminMentorsComponent },
  { path: 'admin/sessions', component: AdminSessionsComponent },
  { path: '**', redirectTo: '' }
];